"""HiveOS Router Lambda — every WebSocket frame lands here.

Routes (CONTRACT.md):
  $connect     register the connection, tell the room someone arrived
  $disconnect  drop the row, tell the room someone left
  $default     every client action

The API's RouteSelectionExpression is `$request.body.action` but only
`$default` is declared, so all actions fall through to one handler. That keeps
the route table static — Phase 2 adds actions, not CloudFormation resources.

Phase 1 handles `hello` and `send_message`; Phase 2 adds `claim_agent` and
`release_agent`; Phase 5 adds `move_avatar`.

Why `hello` exists: API Gateway does not finish establishing a connection
until the $connect integration returns, so post_to_connection against it fails
with GoneException. The client therefore asks for its opening state_snapshot
on the first frame after the socket opens.
"""

import json
import traceback

from shared import agents, broadcast, scheduler, state

OK = {"statusCode": 200}

MAX_USER_ID = 40
MAX_TEXT = 500
MAX_PROMPT = 2000


def lambda_handler(event, context):
    request = event.get("requestContext", {})
    route = request.get("routeKey")
    connection_id = request.get("connectionId")

    try:
        if route == "$connect":
            return _on_connect(event, connection_id)
        if route == "$disconnect":
            return _on_disconnect(connection_id)
        return _on_message(event, connection_id)
    except Exception:
        traceback.print_exc()
        if route == "$connect":
            # Refuse the connection rather than leave a client half-registered.
            return {"statusCode": 500}
        _try_error(connection_id, "internal error")
        return OK


# --- Routes ----------------------------------------------------------------


def _on_connect(event, connection_id):
    """The only route that can read the team: `queryStringParameters` is
    populated on `$connect` and on nothing after it. Everything downstream
    resolves the team from the CONN# index row instead."""
    params = event.get("queryStringParameters") or {}
    user_id = (params.get("user_id") or f"guest-{connection_id[:6]}").strip()[:MAX_USER_ID]
    avatar = (params.get("avatar") or "\U0001f41d")[:8]
    team = state.clean_team(params.get("team"))
    passphrase = params.get("passphrase")
    # Generated by the client, never returned by the server: whoever creates a
    # workspace already holds it, so there is nothing to hand back and no
    # window in which it could be intercepted.
    admin_token = params.get("admin_token")

    # A team nobody has joined before has no budget and no slots. Create them
    # before the member row, so the first person to arrive sees a working board
    # rather than an empty one. Whoever creates a workspace sets its passphrase;
    # this is a no-op on one that already exists.
    state.ensure_team(team, passphrase, admin_token)

    if not state.passphrase_ok(team, passphrase):
        # Refused at the handshake, so no socket and no CONN# row ever exist.
        # The alternative — accept, send an error frame, then close — leaves a
        # connected socket with no team binding for as long as it takes to shut
        # down, and a frame sent in that window resolves to the default
        # workspace. Cheaper to never let it open.
        #
        # Deliberately not logging the passphrase, or whether it was merely
        # absent versus wrong: neither helps debugging and both end up in
        # CloudWatch.
        print(f"[connect] REFUSED connection={connection_id} team={team} — passphrase")
        return {"statusCode": 403}

    # Verified after ensure_team, so the creator of a brand-new workspace is
    # recognised as its administrator on the same connection that made it.
    is_admin = state.admin_token_ok(team, admin_token)

    member = state.add_connection(team, connection_id, user_id, avatar, is_admin)
    print(f"[connect] connection={connection_id} user={user_id} team={team} admin={is_admin}")

    broadcast.broadcast_to_team(
        team,
        {"event": "user_joined", **member},
        exclude=connection_id,
    )
    return OK


def _on_disconnect(connection_id):
    team = state.connection_team(connection_id)
    previous = state.remove_connection(team, connection_id) or {}
    user_id = previous.get("user_id")
    print(f"[disconnect] connection={connection_id} user={user_id} team={team}")

    if user_id:
        broadcast.broadcast_to_team(team, {"event": "user_left", "user_id": user_id})
    return OK


def _on_message(event, connection_id):
    try:
        body = json.loads(event.get("body") or "{}")
    except json.JSONDecodeError:
        return _error(connection_id, "malformed JSON")
    if not isinstance(body, dict):
        return _error(connection_id, "frame must be a JSON object")

    action = body.get("action")
    # Checked before anything reads it as a string. `startswith` below is the
    # first thing that touches it, and on a frame with no action — or one
    # carrying a number or a list — it raised AttributeError into the top-level
    # handler, which answered "internal error". That is the wrong thing twice
    # over: it is the caller's frame that is malformed, not the server, and a
    # stack trace per bad frame is noise in the log that matters.
    if not isinstance(action, str):
        return _error(connection_id, "frame must carry a string action")

    # Resolved from the stored index row, never from the frame. A team the
    # client could name per-message is a team the client could read.
    team = state.connection_team(connection_id)
    print(f"[message] connection={connection_id} team={team} action={action}")

    if action == "hello":
        broadcast.send_to_connection(
            connection_id,
            state.state_snapshot(team, state.connection_is_admin(team, connection_id)),
        )
        return OK

    if action.startswith("admin_"):
        return _admin(team, connection_id, action, body)

    if action == "claim_agent":
        return _claim_agent(team, connection_id, body)

    if action == "release_agent":
        return _release_agent(team, connection_id, body)

    if action == "spawn_agent":
        return _spawn_agent(team, connection_id, body)

    if action == "dismiss_agent":
        return _dismiss_agent(team, connection_id, body)

    if action == "move_avatar":
        return _move_avatar(team, connection_id, body)

    if action == "send_message":
        text = (body.get("text") or "").strip()[:MAX_TEXT]
        if not text:
            return _error(connection_id, "send_message requires text")
        broadcast.broadcast_to_team(
            team,
            {
                "event": "chat_message",
                "user_id": _user_for(team, connection_id, body),
                "text": text,
                "ts": state.now_iso(),
            }
        )
        return OK

    return _error(connection_id, f"unknown action: {action!r}")



# --- Staffing the floor ----------------------------------------------------


def _spawn_agent(team, connection_id, body):
    """Hire an agent onto this floor.

    **Deliberately not an admin action.** Hiring costs nothing — running an
    agent is what spends the budget, and the ceiling governs that identically
    no matter how many desks share it. Requiring the workspace owner to add a
    colleague would be governing the wrong thing, and it would put a
    permissions wall in front of the one interaction this product is now about.

    Every field is truncated server-side rather than rejected, exactly as
    `user_id` and the prompt already are: a client that sends 4KB of persona
    gets a shorter agent, not an error.
    """
    row = state.hire_agent(
        team,
        {
            "name": body.get("name"),
            "role": body.get("role"),
            "tagline": body.get("tagline"),
            "persona": body.get("persona"),
            "character": body.get("character"),
            "project": body.get("project"),
        },
    )

    if row is None:
        return _error(
            connection_id,
            f"this floor is full — {agents.MAX_AGENTS} desks is the limit",
        )

    # The whole room, not just the hirer. A desk appearing on the floor is the
    # most visible thing that happens on this board, and a teammate watching
    # has to see it without a refresh — that is the demo beat.
    broadcast.broadcast_to_team(
        team,
        {
            "event": "agent_spawned",
            "hired_by": _user_for(team, connection_id, body),
            **agents.public(row),
            "status": row["status"],
            "current_user": None,
            "agent_type": row["slot_id"],
            "created_at": row["created_at"],
        },
    )
    return OK


def _dismiss_agent(team, connection_id, body):
    """Take a desk off the floor. Refused while it is working.

    `state.fire_agent` owns both rules and returns the reason it refused, so
    the check and the message cannot drift apart — the alternative was
    duplicating "is it busy" here and letting the two disagree.
    """
    slot_id = body.get("agent_type") or body.get("slot_id")
    if not slot_id:
        return _error(connection_id, "dismiss_agent requires an agent_type")

    refused = state.fire_agent(team, slot_id)
    if refused:
        return _error(connection_id, refused)

    broadcast.broadcast_to_team(
        team,
        {
            "event": "agent_dismissed",
            "agent_type": slot_id,
            "slot_id": slot_id,
            "dismissed_by": _user_for(team, connection_id, body),
        },
    )
    return OK


# --- Administration --------------------------------------------------------


def _admin(team, connection_id, action, body):
    """Privileged actions. Gated on the connection, not on the frame.

    `is_admin` was decided at the handshake and stored on the CONN# row, so a
    client cannot grant itself rights by adding a field to a message — the same
    rule that makes `user_id` trustworthy here.
    """
    if not state.connection_is_admin(team, connection_id):
        return _error(connection_id, "that action needs the workspace admin token")

    if action == "admin_set_budget":
        try:
            budget = int(body.get("token_budget"))
        except (TypeError, ValueError):
            return _error(connection_id, "admin_set_budget requires a number")
        if budget < 0:
            return _error(connection_id, "a budget cannot be negative")

        used, budget = state.set_budget(team, budget)
        print(f"[admin] team={team} budget set to {budget}")
        # Broadcast rather than replied: the ceiling is shared state, and a
        # meter that changed on one screen only would be the exact divergence
        # this product claims to be incapable of.
        broadcast.broadcast_to_team(
            team,
            {
                "event": "token_update",
                "tokens_used": used,
                "token_budget": budget,
                "pct_used": state.pct_used(used, budget),
                "estimated": False,
            },
        )
        return OK

    if action == "admin_rotate_passphrase":
        state.rotate_passphrase(team, body.get("passphrase"))
        print(f"[admin] team={team} passphrase rotated")
        # Everyone already connected stays connected. Rotating locks out the
        # *next* joiner, which is what makes it useful after a demo.
        broadcast.send_to_connection(
            connection_id,
            {"event": "admin_ok", "action": action},
        )
        return OK

    if action == "admin_delete_workspace":
        # Recipients are collected *before* the delete: `delete_team` removes
        # the CONN# rows, and `broadcast_to_team` finds its audience by reading
        # them — so broadcasting afterwards would reach nobody and everyone
        # would sit looking at a workspace that no longer exists.
        watching = state.connection_ids(team)
        removed = state.delete_team(team)
        print(f"[admin] team={team} deleted ({removed} rows, {len(watching)} watching)")
        for target in watching:
            broadcast.send_to_connection(
                target, {"event": "workspace_deleted", "team": team}
            )
        return OK

    return _error(connection_id, f"unknown admin action: {action!r}")


# --- Scheduling ------------------------------------------------------------


def _claim_agent(team, connection_id, body):
    """Take a slot if one is free, otherwise take a place in line."""
    user_id = _user_for(team, connection_id, body)
    prompt = (body.get("prompt") or "").strip()[:MAX_PROMPT]
    if not prompt:
        return _error(connection_id, "claim_agent requires a prompt")

    # The agent asked for — a preference, not a reservation. `claim_any` tries
    # it first and falls back to the next desk rather than queueing someone
    # behind an agent that is sitting idle. Now that the agents are named and
    # genuinely different, the one that *runs* the task is recorded separately
    # and reported back, so a substitution is visible rather than silent.
    # Validated against *this workspace's* desks, not a global list — two
    # boards no longer have the same roster. An id that is not on this floor
    # is dropped to "no preference" rather than rejected, which is already how
    # a preference for a busy desk behaves.
    #
    # Read once and handed to `claim_any` below. It needs the same list, and
    # this is the hottest path in the product — letting both read it would be
    # two identical queries on every single task.
    slots = scheduler.slot_ids(team)
    requested = body.get("agent_type")
    if requested not in slots:
        requested = None

    task_id = scheduler.new_task_id()

    if not state.acquire_user_admission(team, user_id, task_id):
        return _error(connection_id, "you already have an agent running or queued")

    slot_id = None
    try:
        slot_id = scheduler.claim_any(team, requested, user_id, slots)

        if slot_id is None:
            scheduler.enqueue(
                team, user_id, requested, prompt, connection_id, task_id=task_id
            )
            scheduler.broadcast_queue(team)
            return OK

        # Announce BUSY *before* handing the task to SQS. The slot is already BUSY
        # in DynamoDB, so this frame is accurate either way — but dispatching first
        # lets a fast-failing task post its reply ahead of this frame, and a client
        # that sees BUSY arrive after the release is left showing a slot that never
        # goes idle again.
        scheduler.broadcast_slot(team, slot_id, "BUSY", user_id)
        scheduler.dispatch(
            team, slot_id, user_id, requested, prompt, connection_id, task_id=task_id
        )
        return OK
    except Exception:
        if slot_id:
            scheduler.set_idle(team, slot_id, expected_holder=user_id)
        else:
            state.release_user_admission(team, user_id)
        raise


def _release_agent(team, connection_id, body):
    """Manual release. The Agent Runner also releases automatically when a
    task ends — this exists so a wedged demo slot can be freed from the UI.

    Who may free a desk:

      - whoever is sitting at it. The UI only draws the button for the desk
        running *your* task, and this is the server-side half of that — until
        now there was no server-side half, and any connected client could send
        `{"action": "release_agent", "agent_type": "coder"}` and cut short a
        teammate's running task.
      - a workspace admin, for the case the button was written for: a runner
        died holding a desk and the person it belonged to has closed the tab.
        Restricting this to the holder alone would leave the escape hatch
        working only for people who do not need it.

    An already-idle desk is neither an error nor a release. There is nobody to
    authorise against and nothing to free, so it only pokes the dispatcher.
    That is scheduler housekeeping rather than a privilege: it can start work
    that is already queued, at a desk that is already free, and nothing else.
    `ws_smoke.py` leans on exactly this to make a pinned handoff move.

    Authorisation reads the CONN# row directly rather than going through
    `_user_for`, whose last resort is the `user_id` on the frame. That
    fallback is fine for labelling a chat line and wrong here — it would let a
    caller name themselves the holder.
    """
    # One GetItem answers both questions: does this desk exist on this floor,
    # and who is sitting at it. The roster used to be a module constant that
    # could be checked for free; now that it is data, reading the one row we
    # are about to act on beats querying the whole floor to validate an id and
    # then reading that row anyway.
    agent_type = body.get("agent_type")
    desk = state.agent_row(team, agent_type) if agent_type else None
    if not desk:
        return _error(connection_id, f"unknown agent_type: {agent_type!r}")

    holder = desk.get("current_user")
    if holder is None:
        scheduler.dispatch_next(team)
        return OK

    requester = state.connection_user(team, connection_id)
    if holder != requester and not state.connection_is_admin(team, connection_id):
        print(f"[release] REFUSED connection={connection_id} slot={agent_type}")
        return _error(connection_id, f"{agent_type} is not yours to release")

    # The holder read above is what the conditional write expects, so losing
    # that race means the desk freed itself in between — which is the outcome
    # the caller asked for. `release_and_dispatch` absorbs it either way.
    scheduler.release_and_dispatch(team, agent_type, expected_holder=holder)
    return OK


def _move_avatar(team, connection_id, body):
    """Move this connection's avatar and tell the room.

    Coordinates are percentages of the canvas (0-100), not pixels, so three
    browsers at different widths agree on where everyone is standing —
    "identical on every screen" is the product's whole claim, and a pixel
    coordinate would break it on the first mismatched window.

    The position is stored per *connection* — the CONN# row is what carries it —
    but drawn per user: `state_snapshot.members[]` deliberately omits
    `connection_id`, so the client dedupes by `user_id` and a second tab moves
    the same marker. One person, one marker. See CONTRACT.md.
    """
    x, y = _coord(body.get("x")), _coord(body.get("y"))
    if x is None or y is None:
        return _error(connection_id, "move_avatar requires numeric x and y")

    user_id = state.move_connection(team, connection_id, x, y)
    if user_id is None:
        # The row is gone — the socket is mid-disconnect. Nothing to broadcast,
        # and resurrecting it would put a ghost in everyone's member count.
        return OK

    broadcast.broadcast_to_team(
        team, {"event": "avatar_moved", "user_id": user_id, "x": x, "y": y}
    )
    return OK


def _coord(value):
    """A canvas coordinate clamped to 0-100, or None if it is not a number.

    `bool` is excluded deliberately: it is a subclass of `int` in Python, so
    `{"x": true}` would otherwise be accepted and silently become 1.
    """
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return None
    if value != value or value in (float("inf"), float("-inf")):  # NaN / inf
        return None
    return round(max(0.0, min(100.0, float(value))), 2)


def _already_working(team, user_id):
    """One task per user at a time.

    Without this a double-clicked "Get Agent" button lets one person hold both
    slots, which is precisely the unfair-monopoly behaviour the product claims
    to prevent — and it would happen live on the recording.

    One query rather than a get per slot plus a queue query: this runs on the
    claim path, which is the interaction the whole demo hangs on.

    A queued *handoff* counts, because its QUEUE# row carries the requester's
    id like any other. That is the reading we want: their chain is still
    running, it just moved desks, and letting them start a second one while a
    second leg waits is exactly the double-claim this prevents.
    """
    if state.is_user_active(team, user_id):
        return True
    for item in state.query_team(team):
        sk = item["SK"]
        if sk.startswith("AGENT#") and item.get("current_user") == user_id:
            return True
        if sk.startswith("QUEUE#") and item.get("user_id") == user_id:
            return True
    return False


# --- Helpers ---------------------------------------------------------------


def _user_for(team, connection_id, body):
    """Trust the CONN# row over the frame — the row is what $connect recorded."""
    return state.connection_user(team, connection_id) or body.get("user_id") or "unknown"


def _error(connection_id, message):
    broadcast.send_to_connection(connection_id, {"event": "error", "message": message})
    return OK


def _try_error(connection_id, message):
    """Best-effort error reply from the top-level exception handler."""
    try:
        _error(connection_id, message)
    except Exception:
        traceback.print_exc()
